export const userTypes = {
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_SERVER_ERROR: 'SIGN_IN_SERVER_ERROR',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',

    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',

    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    SIGN_UP_USER_ERROR: 'SIGN_UP_USER_ERROR',
    SIGN_UP_SERVER_ERROR: 'SIGN_UP_SERVER_ERROR',



    // SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    // SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',


    // SET_CURRENT_USER: 'SET_CURRENT_USER',
    // SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    // SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    // SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    // SIGN_UP_FAILED_AUTH: 'SIGN_UP_FAILED_AUTH',
    // RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    // RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
    // RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
}