export const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',

    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    SIGN_UP_FAILED_AUTH: 'SIGN_UP_FAILED_AUTH',

    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

    RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
}