export const userTypes = {
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_SERVER_ERROR: 'SIGN_IN_SERVER_ERROR',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',

    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',

    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    SIGN_UP_USER_ERROR: 'SIGN_UP_USER_ERROR',
    SIGN_UP_SERVER_ERROR: 'SIGN_UP_SERVER_ERROR',

    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',

}