export const plantsTypes = {
    ADD_NEW_PLANT_START: 'ADD_NEW_PLANT_START',
    FETCH_PLANTS_START: 'FETCH_PLANTS_START',
    SET_PLANTS: 'SET_PLANTS',
    DELETE_PLANT_START: 'DELETE_PLANT_START',

    FETCH_A_PLANT_START: 'FETCH_A_PLANT_START',
    SET_A_PLANT: 'SET_A_PLANT',
}